#Github Workflow to find and notify about misspellings
#
#SPDX-FileCopyrightText: 2025-2026 German Federal Office for Information Security (BSI) <https://www.bsi.bund.de>
#Software-Engineering: 2025-2026 Intevation GmbH <https://intevation.de>
#SPDX-License-Identifier: Apache-2.0

name: "Codespell spelling check"

on:
  push:
    paths-ignore:
      - '.github/**'
  pull_request:
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  codespell:
    name: Find and notify about common misspellings
    runs-on: ubuntu-latest
    # This should not fail the whole workflow run
    continue-on-error: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        repository: csaf-tools/csaf-action
    - name: Run codespell
      uses: codespell-project/actions-codespell@v2
      with:
        check_hidden: true
        check_filenames: true
        # for www.bsi.bund.de
        ignore_words_list: bund
