#SPDX-FileCopyrightText: 2025-2026 German Federal Office for Information Security (BSI) <https://www.bsi.bund.de>
#Software-Engineering: 2025-2026 Intevation GmbH <https://intevation.de>
#SPDX-License-Identifier: Apache-2.0
#
name: "Shellcheck"
on:
  push:
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: csaf-tools/csaf-action
          path: csaf-action
          ref: main
      - uses: actions/checkout@v4
        with:
          path: csaf-action-test
      - name: Extract commands
        run: ./csaf-action-test/generate_local_execution.sh ./csaf-action/action.yml
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          severity: warning
